info = input('Digite algo:')
print('Qual o tipo primitivo? ', type(info))
print('Is numeric? ', info.isnumeric())
print('Is alpha? ', info.isalpha())
print('Have space? ', info.isspace())
print('Is UPPER CASE?', info.isupper())
print('Is lower case? ', info.islower())
print('Is Captalized? ', info.istitle())
